# Generated by Django 4.2.5 on 2023-12-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_flipkartdatabase_gemdatabase_delete_flipkartdata_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GemDatabase',
            new_name='GemniData',
        ),
    ]
