# Generated by Django 4.2.5 on 2023-12-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_maindatabase_delete_gemnidata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maindatabase',
            old_name='ratings',
            new_name='product_ratings',
        ),
    ]
